spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: cursos
          uri: http://localhost:8081
          predicates:
            - Path=/cursos/**
        - id: disciplinas
          uri: http://localhost:8081
          predicates:
            - Path=/disciplinas/**
        - id: alunos
          uri: http://localhost:8082
          predicates:
            - Path=/alunos/**
