spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: api-cursos
          uri: http://localhost:8081
          predicates:
            - Path=/cursos/**
            - Path=/disciplinas/**
        - id: api-alunos
          uri: http://localhost:8082
          predicates:
            - Path=/alunos/**
